Require a working git installation for propogate script.

diff --git a/scripts/propagate b/scripts/propagate
--- a/scripts/propagate
+++ b/scripts/propagate
@@ -25,6 +25,13 @@ if (( UID != 0 )); then
   exit 1
 fi
 
+GIT=$(type -P git)
+GIT=${GIT:-$(type -P /opt/clusterware/opt/git/bin/git)}
+if [ -z "$GIT" ]; then
+  echo "$0: could not find a working git installation; please install git!"
+  exit 1
+fi
+
 src_dir="${alces_SOURCE_DIR:-$(mktemp -d /tmp/clusterware.XXXXXXXX)}"
 
 if [ ! -f "${src_dir}"/scripts/control.vars.sh ]; then
@@ -77,15 +84,15 @@ done
 title "Preparing public repository contents"
 mkdir -p "${src_dir}/tmp/repos"
 doing "Handlers"
-git clone https://github.com/alces-software/clusterware-handlers.git "${src_dir}"/tmp/repos/clusterware-handlers &>/dev/null
+$GIT clone https://github.com/alces-software/clusterware-handlers.git "${src_dir}"/tmp/repos/clusterware-handlers &>/dev/null
 tar -C "${src_dir}"/tmp/repos/clusterware-handlers -czf "${prop_dir}/clusterware-handlers.tar.gz" .
 say_done $?
 doing "Gridware"
-git clone https://github.com/alces-software/packager-base.git "${src_dir}"/tmp/repos/packager-base &>/dev/null
+$GIT clone https://github.com/alces-software/packager-base.git "${src_dir}"/tmp/repos/packager-base &>/dev/null
 tar -C "${src_dir}"/tmp/repos/packager-base -czf "${prop_dir}/packager-base.tar.gz" .
 say_done $?
 doing "Sessions"
-git clone https://github.com/alces-software/clusterware-sessions.git "${src_dir}"/tmp/repos/clusterware-sessions &>/dev/null
+$GIT clone https://github.com/alces-software/clusterware-sessions.git "${src_dir}"/tmp/repos/clusterware-sessions &>/dev/null
 tar -C "${src_dir}"/tmp/repos/clusterware-sessions -czf "${prop_dir}/clusterware-sessions.tar.gz" .
 say_done $?
 
